PS C:\Users\HP> CD C:\Users\HP\CascadeProjects\PC_Explorer_Android
PS C:\Users\HP\CascadeProjects\PC_Explorer_Android> git remote remove origin
PS C:\Users\HP\CascadeProjects\PC_Explorer_Android> git remote add origin https://github.com/ilyas1305/MostakshifAfaqPC-Android.git
PS C:\Users\HP\CascadeProjects\PC_Explorer_Android> git push -u origin main
Enumerating objects: 24, done.
Counting objects: 100% (24/24), done.
Delta compression using up to 16 threads
Compressing objects: 100% (14/14), done.
Writing objects: 100% (24/24), 11.99 KiB | 682.00 KiB/s, done.
Total 24 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
To https://github.com/ilyas1305/MostakshifAfaqPC-Android.git
 * [new branch]      main -> main
branch 'main' set up to track 'origin/main'.
PS C:\Users\HP\CascadeProjects\PC_Explorer_Android>
